In [3]:
# 数值计算
# numpy  = numerical python  

In [1]:
# ndarray     数组
import numpy as np
np.arange(5)  #生成len为5的数组

array([0, 1, 2, 3, 4])

In [8]:
list(np.arange(5))

[0, 1, 2, 3, 4]

In [16]:
# 多维数组
data=np.random.randn(2,3)
data

array([[-0.60860919, -0.538071  ,  0.84088005],
       [ 0.41630219,  0.69928232, -0.55406086]])

In [17]:
data*2  #所有的元素都同时乘以2

array([[-1.21721838, -1.076142  ,  1.68176009],
       [ 0.83260438,  1.39856464, -1.10812172]])

In [23]:
# 列表转数组
data1 = [3,4,6,7]
np.array(data1)


array([3, 4, 6, 7])